# Generated by Django 4.2.1 on 2023-10-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Geneapp', '0002_profile_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
